# Form implementation generated from reading ui file 'e:\Codes\Qt Projects\Endo_Raman_Collector\src\CollectorWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CollectorWindow(object):
    def setupUi(self, CollectorWindow):
        CollectorWindow.setObjectName("CollectorWindow")
        CollectorWindow.resize(981, 989)
        font = QtGui.QFont()
        CollectorWindow.setFont(font)
        CollectorWindow.setStyleSheet("QWidget:window {\n"
"    /* Borders around the code editor and debug window */\n"
"    background-color: #263238;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CollectorWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(CollectorWindow)
        self.splitter.setAutoFillBackground(False)
        self.splitter.setStyleSheet("    background-color: #263238;")
        self.splitter.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.originView = QChartView(self.layoutWidget)
        self.originView.setObjectName("originView")
        self.horizontalLayout.addWidget(self.originView)
        self.catView = QChartView(self.layoutWidget)
        self.catView.setObjectName("catView")
        self.horizontalLayout.addWidget(self.catView)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.catedsView = QChartView(self.layoutWidget1)
        self.catedsView.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.catedsView.setObjectName("catedsView")
        self.verticalLayout.addWidget(self.catedsView)
        self.predsView = QChartView(self.layoutWidget1)
        self.predsView.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.predsView.setObjectName("predsView")
        self.verticalLayout.addWidget(self.predsView)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(41)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"    color: rgb(159, 255, 64);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(175, 175, 175);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(41)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color:rgb(66, 255, 246);\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(175, 175, 175);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"QPushButton:disabled{\n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(41)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: rgb(94, 56, 224);\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(175, 175, 175);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_del = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_del.sizePolicy().hasHeightForWidth())
        self.pushButton_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(41)
        font.setBold(False)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"}")
        self.pushButton_del.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/usertrashfull_92826.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_del.setIcon(icon)
        self.pushButton_del.setIconSize(QtCore.QSize(56, 56))
        self.pushButton_del.setObjectName("pushButton_del")
        self.gridLayout.addWidget(self.pushButton_del, 5, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(41)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color: rgb(222, 165, 55);\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(175, 175, 175);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(41)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"    color: rgb(69, 255, 120);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(175, 175, 175);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"QPushButton:disabled{\n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 4, 0, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(41)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"    color: rgb(244, 74, 77);\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(175, 175, 175);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    \n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_1.setCheckable(True)
        self.pushButton_1.setChecked(False)
        self.pushButton_1.setAutoRepeat(False)
        self.pushButton_1.setDefault(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(41)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    color: rgb(222, 114, 58);\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(175, 175, 175);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"QPushButton:disabled{\n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 5, 0, 1, 1)
        self.pushButton_stop = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_stop.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(29)
        font.setBold(False)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton{\n"
"    color: rgb(139, 69, 19);\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #AFBDC4;\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"QPushButton:disabled{\n"
"    \n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout.addWidget(self.pushButton_stop, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(41)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    color: rgb(224, 76, 244);\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(175, 175, 175);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 3, 1, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Chiller")
        font.setPointSize(29)
        font.setBold(False)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"    color:rgb(247, 0, 124);\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #AFBDC4;\n"
"    background-color: rgb(180, 148, 200);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #FFFFFF;\n"
"}\n"
"")
        self.pushButton_start.setCheckable(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Curlz MT")
        font.setPointSize(41)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(173, 142, 180);\n"
"    border-radius:15px;\n"
"    color: rgb(58, 127, 224);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(175, 175, 175);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(74, 97, 109);\n"
"}\n"
"QPushButton:disabled{\n"
"    color: rgb(124, 124, 124);\n"
"};")
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 4, 1, 1, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.gridLayout.setRowStretch(5, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.splitter)
        self.tableWidget = QtWidgets.QTableWidget(CollectorWindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: #263238;\n"
"    color: #546E7A;\n"
"    outline: 0;\n"
"    border: 2px solid transparent;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    color: #AFBDC4;\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected {\n"
"    color: #ffffff;\n"
"    background: transparent;\n"
"}")
        self.tableWidget.setRowCount(9)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 2)

        self.retranslateUi(CollectorWindow)
        QtCore.QMetaObject.connectSlotsByName(CollectorWindow)

    def retranslateUi(self, CollectorWindow):
        _translate = QtCore.QCoreApplication.translate
        CollectorWindow.setWindowTitle(_translate("CollectorWindow", "光谱采集互动"))
        self.pushButton_5.setText(_translate("CollectorWindow", "5"))
        self.pushButton_4.setText(_translate("CollectorWindow", "4"))
        self.pushButton_2.setText(_translate("CollectorWindow", "2"))
        self.pushButton_3.setText(_translate("CollectorWindow", "3"))
        self.pushButton_7.setText(_translate("CollectorWindow", "7"))
        self.pushButton_1.setText(_translate("CollectorWindow", "1"))
        self.pushButton_1.setShortcut(_translate("CollectorWindow", "F5"))
        self.pushButton_9.setText(_translate("CollectorWindow", "9"))
        self.pushButton_stop.setText(_translate("CollectorWindow", "STOP"))
        self.pushButton_6.setText(_translate("CollectorWindow", "6"))
        self.pushButton_start.setText(_translate("CollectorWindow", "START"))
        self.pushButton_8.setText(_translate("CollectorWindow", "8"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
from PyQt6.QtCharts import QChartView
